name: gaussian_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.8
  - python=3.9
  - pip=23.0
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - plyfile
  - tqdm
  - ninja
  - wheel
  - pip:
    - opencv-python
    - scipy
    - matplotlib
    - imageio
    - joblib